import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faTrash,
  faFolder,
  faFolderOpen,
  faFile,
  faShare,
  faCircleUser,
  faDiagramProject,
  faGears,
  faAnglesLeft,
  faAnglesRight,
  faRetweet,
  faPlus,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faSquareXmark,
  faSquareCheck,
  faCircleInfo,
  faSortUp,
  faSortDown,
  faDownload,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faXmark,
  faCircleCheck,
  faSquarePlus,
  faBars,
  faLayerGroup,
  faChevronLeft,
} from '@fortawesome/free-solid-svg-icons';
import {
  faPenToSquare,
  faShareFromSquare,
  faCommentDots,
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faTrash,
  faFolder,
  faFolderOpen,
  faFile,
  faShare,
  faPenToSquare,
  faCircleUser,
  faDiagramProject,
  faGears,
  faShareFromSquare,
  faAnglesLeft,
  faAnglesRight,
  faRetweet,
  faPlus,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faCommentDots,
  faSquareXmark,
  faSquareCheck,
  faCircleInfo,
  faSortUp,
  faSortDown,
  faDownload,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faXmark,
  faCircleCheck,
  faSquarePlus,
  faBars,
  faLayerGroup,
  faChevronLeft
);

export default FontAwesomeIcon;
