# Use python:alpine which is a stripped-down version of Python using Alpine Linux
FROM python:3.13-alpine3.21

# APK is the package manager for Alpine Linux, and musl-dev/gcc are required for building some Python packages
# Also installing Poetry in the same layer
RUN apk add --no-cache gcc musl-dev && \
    pip install poetry

# Set workdir
WORKDIR /app

# Copy only Poetry files first for better caching
COPY pyproject.toml poetry.lock ./

# Install dependencies (no venv, system-wide for Docker)
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Copy the rest of your app
COPY . .

# Expose port
EXPOSE 8008

# Start FastAPI
CMD ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8008"]
