# Use official Node.js image for development environment
FROM node:23-alpine
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first (to cache dependencies)
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./ .

# Expose the port that the Vue.js dev server will run on
EXPOSE 8888

# Run the Vue.js development server
CMD ["npm", "run", "dev:docker"]
